### ISSUE TITLE
[문의] pip 설치 실패 

### ISSUE THREAD

**Issue by j2doll** [HongJunhyoung/Snowball#1]
- pip로 설치 시도를 하였습니다.
```cmd
C:\Users\Hello>pip3 install -U snowball
```

- 설치 실패
```
Requirement already satisfied: snowball in c:\users\wjj\appdata\local\programs\python\python311\lib\site-packages\snowball-0.5.2+0.g1c2ca65.dirty-py3.11.egg (0.5.2+0.g1c2ca65.dirty)
Requirement already satisfied: numpy>=1.18.4 in c:\users\wjj\appdata\local\programs\python\python311\lib\site-packages (from snowball) (1.24.2)
Requirement already satisfied: pandas>=1.0.3 in c:\users\wjj\appdata\local\programs\python\python311\lib\site-packages (from snowball) (2.0.0)
Requirement already satisfied: tqdm>=4.45.0 in c:\users\wjj\appdata\local\programs\python\python311\lib\site-packages (from snowball) (4.65.0)
Collecting plotly>=5.1.0
  Using cached plotly-5.14.1-py2.py3-none-any.whl (15.3 MB)
Collecting scipy>=1.4.1
  Using cached scipy-1.10.1-cp311-cp311-win_amd64.whl (42.2 MB)
Collecting kaleido>=0.2.1
  Using cached kaleido-0.2.1-py2.py3-none-win_amd64.whl (65.9 MB)
Requirement already satisfied: Ipython in c:\users\wjj\appdata\local\programs\python\python311\lib\site-packages (from snowball) (8.11.0)
Collecting PyPortfolioOpt
  Using cached pyportfolioopt-1.5.2-py3-none-any.whl (61 kB)
Collecting sklearn
  Using cached sklearn-0.0.post4.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\WJJ\AppData\Local\Temp\pip-install-zgtxrtiu\sklearn_86786c924cdc49929fdb90763b6459cb\setup.py", line 10, in <module>
          LONG_DESCRIPTION = f.read()
                             ^^^^^^^^
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 2: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

- 어떤 원본 소스를 수정하면 되는지 문의 드립니다.

- github 에서 ```git clone  https://github.com/HongJunhyoung/Snowball.git``` 후, ```python setup.py install``` 해도 오류 메시지 나옵니다.

**Comment by HongJunhyoung** [comment]
피드백 감사합니다. 제가 리눅스만 써서 윈도우에서 저런 이슈가 있는지 몰랐었네요. 수정했으니 다시 설치해보시기 바랍니다. 감사합니다.

**Comment by HongJunhyoung** [comment]
피드백 감사합니다. 제가 리눅스만 써서 윈도우에서 저런 이슈가 있는지 몰랐었네요. 수정했으니 다시 설치해보시기 바랍니다. 감사합니다.
